Desc english
adam-broussard/bestreads pull request #19
Opened 2022-04-19 02:33 UTC by youngant

This should solve #15. Adds a column indicating if the description is in English. The recognition is slow (takes a few minutes), so this should really only be run once.

2022-04-19 02:41 UTC, youngant commented
Do I just need to add the missing package to the setup.py to fix the failed check? No way to fix that automatically?

2022-04-19 14:06 UTC, adam-broussard commented
Hmm I'm not sure... You'll definitely want to add it to `setup.py` because if we import it, it is a dependency.  That may or may not fix the linter - if not, you'll likely have to add it to the [pip install](https://github.com/adam-broussard/bestreads/blob/b5c6d5bbfb94dbfd8cc27d4fac0d19788ef506a3/.github/workflows/pylint.yml#L24) for the environment the linter is run in.  I would love for that to just pull the dependencies from `setup.py`, but I'm not sure how to make it happen...  It might be as simple as getting the environment to install `bestreads`, in which case it should also install the relevant listed dependencies so we only have to change it in one place?

2022-04-19 14:15 UTC, adam-broussard commented
[This](https://github.com/astropy/astropy/blob/main/pip-requirements) seems to indicate that my comment above is correct - maybe you could try getting rid of the packages I added in the yml file and have it just install bestreads itself (with langdetected added to setup.py)?  I think that should do it.

2022-04-19 16:37 UTC, youngant commented
I think the package installation is fixed now. All we should need to do is add the package to setup.py.

2022-04-19 23:59 UTC, adam-broussard requested changes
Check these out and let me know what you think!

2022-04-19 23:59 UTC, adam-broussard commented on bestreads/text.py
> +        data (pandas.DataFrame): The DataFrame constaining the descriptions of the books.
```suggestion
        data (pandas.DataFrame): The DataFrame containing the descriptions of the books.
```

2022-04-20 00:12 UTC, youngant commented on bestreads/text.py
> +def add_english_column(data):
It's probably better to return a copy like you suggested.

2022-04-20 13:45 UTC, adam-broussard commented
Just as a heads-up, there is a re-request review button where you select the reviewer, so if you are done with changes, you can click that to ping me to start the approval process again!

2022-04-20 14:14 UTC, youngant commented
Thanks, I wasn't sure if there was a way to do something like that.

2022-04-20 14:15 UTC, adam-broussard approved these changes

2022-04-20 14:16 UTC, merged