Fixed preprocessed data reading and writing
adam-broussard/bestreads pull request #36
Opened 2022-04-25 00:23 UTC by youngant

This should resolve #20 and #35. The analysis notebook is now fixed to read in the preprocessed data.

2022-04-25 13:59 UTC, adam-broussard requested changes
Just one tiny change.  I would say that I have a mild preference for keeping the data the notebooks work with in the `notebooks` folder, but if you think it is better served in the root folder that is fine

2022-04-25 13:59 UTC, adam-broussard commented on notebooks/2_Analysis.ipynb
> +    "datadir = '../data/processed/'\n",
I would recommend that we rename `datadir` to `data_dir` or similar to keep with our other variable naming scheme

2022-04-25 14:13 UTC, adam-broussard commented
I am also now realizing that this doesn't solve #20 because it does not include a script that performs all text cleaning

2022-04-25 14:19 UTC, adam-broussard requested changes

2022-04-25 14:19 UTC, adam-broussard commented on notebooks/2_Analysis.ipynb
> +    "    datadir + 'goodreads_books_test_processed.csv')\n",
Note that when reading these in, we must use `read_csv('...', index_col=0)` to read the indices in properly since we saved them as a column in the previous notebook.

2022-04-25 14:21 UTC, adam-broussard commented on notebooks/2_Analysis.ipynb
> +    "    datadir + 'goodreads_books_test_processed.csv')\n",
I also just realized that the same is also true of the TF-IDF table read-in on the next line

2022-04-26 01:47 UTC, youngant commented on notebooks/2_Analysis.ipynb
> +    "datadir = '../data/processed/'\n",
Fine by me! I was being consistent with your `savedir` (although I would have done the same thing anyway).

2022-04-26 01:51 UTC, youngant commented
> I am also now realizing that this doesn't solve #20 because it does not include a script that performs all text cleaning

I don't think we need a script to do that since the notebook already does it. (My suggestion had really only been to do one or the other.) A user should be able to just export the notebook to a python file anyway. But I'm okay with just making a script version of the notebook if you want it.

2022-04-26 01:53 UTC, youngant commented on notebooks/2_Analysis.ipynb
> +    "    datadir + 'goodreads_books_test_processed.csv')\n",
Thanks, didn't know that one!

2022-04-26 03:01 UTC, adam-broussard commented on notebooks/2_Analysis.ipynb
> +    "datadir = '../data/processed/'\n",
..... Good point haha.  I'll have to fix those in my stuff.

2022-04-26 03:01 UTC, adam-broussard commented
That's fair, sounds reasonable!

2022-04-26 03:02 UTC, adam-broussard approved these changes

2022-04-26 14:38 UTC, merged